### PR TITLE
Gallery: fix image size select

### PR DESCRIPTION
**Pull request by sergsadovyi**

### CODE REVIEW

**Comment by designerbrent** [comment]
One quick (i hope) issue to address on this: It is forcing all the images into a horizontal aspect ratio by cropping the images to a horizontal image. Can we display the image in the correct aspect ratio?

**Review by designerbrent — CHANGES_REQUESTED** [review]
see comment above.

**Comment by sergsadovyi** [comment]
Added new class to ALPS for this fix. Please merge the https://github.com/adventistchurch/alps/issues/490 first

**Comment by designerbrent** [comment]
I've merged the https://github.com/adventistchurch/alps/pull/490 PR but haven't seen any change in the behavior of the gallery yet.

**Comment by sergsadovyi** [comment]
adventistchurch/alps#490 adds `u-background--contain` class to the ALPS css. Current PR will change Gallery behaivor.

**Comment by designerbrent** [comment]
I'm seeing no change in the gallery, even after pulling this most recent change of this PR. What I'm seeing on the back-end of this, and a newly inserted gallery is this: 

## Backend
2020-08-05 at 7 21 AM

## Frontend
2020-08-05 at 7 22 AM

**Comment by sergsadovyi** [comment]
Fixed

**Review by designerbrent — APPROVED** [review]

**Pull request merged**
