### PR TITLE
fix(latest-posts): tag list limit

### PR DESCRIPTION
**Pull request by sergsadovyi**
Increased limit in query from 100 to 999. Autocomplete is also possible, but requires more complex refactoring.
Should the autocomplete be added?
@designerbrent

### CODE REVIEW

**Comment by designerbrent** [comment]
@sergsadovyi Yes, please switch these to `autocomplete`

**Comment by sergsadovyi** [comment]
Autocomplete for Latest Posts component will have conflicts with #36 . Let's merge this PR. And I'll add autocomplete while refactoring the component in #36 

@designerbrent

**Comment by sergsadovyi** [comment]
1. Added custom REST endpoint to get all tags. The default endpoint has a limit of 100.
2. It is possible to select multiple tags. Suggestions are showed while typing the tag name.
3. The `FormTokenField` component from Core is used to handle tag selection.
4. Gutenberg has a new component `ComboboxControl`, that will fit better our needs. It shows the dropdown list of items without the need of typing some symbols. But we should wait when the Gutenberg components will be updated in Wordpress Core.
https://developer.wordpress.org/block-editor/components/combobox-control/

**Review by designerbrent — APPROVED** [review]

**Comment by designerbrent** [comment]
@sergsadovyi regarding item 4 above, are you thinking we should use what we have here and add the `ComboboxControl` in later, or wait to merge this till then?

**Comment by sergsadovyi** [comment]
I think it is better to merge this PR. It fixes the bug of some tags not available in suggestions on websites with more than 100 tags.
When Wordpress Gutenberg blocks update to new version, I'll change the input to `ComboboxControl`.

**Pull request merged**
