### PR TITLE
v3.23 Media Testimonies Gutenberg block development.

### LINKED ISSUE #23: Build out Media Testimonies Gutenberg Block
Build out the Media Testimonies section that can be found on https://www.adventist.org/ as a Gutenberg Block.

Screen Shot 2020-03-27 at 9 34 13 AM

### PR DESCRIPTION
**Pull request by kelscahill**
Closes #23

### CODE REVIEW

**Review by designerbrent — CHANGES_REQUESTED** [review]
I think this is close. I have two concerns: 

## Unable to Type in "Enter Quote" area
When I try to enter text in the place you have `Enter Quote`, the cursor doesn't show there. Also, I can't paste text into that box.
2020-04-10 at 3 12 PM

## Extra blocks that can be added
Extra blocks can be added to the carousel that are not part of the `ALPS Media Testimony Block`. I tried adding a paragraph and it added but didn't look great. Can we limit what shows there to just the `ALPS Media Testimony Block`?

2020-04-10 at 3 15 PM

**Comment by kelscahill** [comment]
@designerbrent Those updates are now made. Just let me know if you still have the cursor issue and what browser you are testing in. Locally it was hard for me to replicate the issue.

**Comment by designerbrent** [comment]
@kelscahill Regarding the extra blocks, this took care of that. 

The the `Unable to Type in "Enter Quote" area`, I'm wondering if it's my install. I had the same problem in both Firefox and Chrome on another block. I can type on both blocks, but I can't paste into it, though on some live sites, it works fine. I probably need to install a new local dev environment as it's a bit mucked up from all the testing.

The only issue left is that the preview images are only showing at a short height for me on both Firefox and Chrome.
2020-04-21 at 3 23 PM

Thanks.

**Comment by kelscahill** [comment]
@designerbrent I believe the image issue was due to the new Wordpress version and I implemented a fix. Let me know if you have any other issues.

I am still unable to replicate the quote field issue, so something on your local may need to be updated.

**Review by designerbrent — APPROVED** [review]

**Comment by designerbrent** [comment]
@kelscahill Please fix the conflicts and then this is good to go.

**Comment by kelscahill** [comment]
@designerbrent I was finally able to replicate the issue with not being able to `paste`. Seems like the setting `isSelected: false,` prevents it. The merge conflict is fixed and you should be able to paste now.

**Pull request merged**
