### PR TITLE
#342 CTA block development

### PR DESCRIPTION
**Pull request by kelscahill**
Closes #342 in ALPS-WP. This PR will need to be merged as well: https://github.com/adventistchurch/alps-wordpress/pull/359

Also, the image does not have the responsive sizes, but it will be addressed in https://github.com/adventistchurch/alps-wordpress/issues/334

### CODE REVIEW

**Review by designerbrent — CHANGES_REQUESTED** [review]
@kelscahill A few comments: 

- [x] I can't find a way to remove the image once it has been set.
- [x] if we don't include an image in the CTA, the text should flow the full width.
2019-10-08 at 11 17 AM
- [x] There are issues with more then one CTA block on a page. When an image was not included on the second CTA, the image didn't load anywhere.
- [x] When more then one, CTA is used, after saving, we get an error saying the block had and error and it can't be previewed.
2019-10-08 at 11 24 AM

**These are very important tweaks that we need to make this work well.**

**Comment by kelscahill** [comment]
This is ready for review!

**Comment by designerbrent** [comment]
@kelscahill I'm sure I'm missing something but the CTA block isn't showing for me at all when I test this branch. Do I need to run something to compile it?

**Comment by kelscahill** [comment]
@designerbrent I just rebuilt the files. That could have been the issue. Try again and let me know if it works.

**Comment by designerbrent** [comment]
@kelscahill Still no luck. Is there a cache that I should be clearing?

**Comment by kelscahill** [comment]
@designerbrent The gutenberg blocks do cache to some extend. Try in incognito mode. Can you confirm you did pull the latest files from the branch and added them to your local plugins directory?

**Comment by designerbrent** [comment]
@kelscahill I'm stumped. I have the `v3.342-cta-block` branch checked out. I removed it to prove to myself that I was on the right install. I have tried incognito mode. I have tried deleting the `/uploads/cache` folder. 

All of these has been to on effect. Are you sure that everything got checked in?

**Review by designerbrent — APPROVED** [review]

**Comment by designerbrent** [comment]
So i found my problem. I was not running the updated version of the theme, thus it wasn't showing. Oops. I pulled that and it worked fine.

**Comment by kelscahill** [comment]
Okay great! I was troubleshooting, but couldn't seem to replicate. Glad you were able to get it working.

**Pull request merged**
